# Generated by Django 4.2.7 on 2023-12-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.TextField(max_length=255)),
                ('book_description', models.TextField(max_length=255)),
                ('book_url', models.TextField(max_length=255)),
                ('print_length', models.IntegerField()),
                ('language', models.TextField()),
                ('author_name', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
