# Generated by Django 5.0 on 2023-12-31 07:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='cart',
            name='time_order',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 14, 49, 44, 574007)),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
