# Generated by Django 4.2.7 on 2023-12-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0002_alter_book_book_description_alter_book_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.TextField(max_length=40),
        ),
    ]
