# Generated by Django 4.2.7 on 2023-12-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0003_alter_book_author_name_alter_book_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.ImageField(storage='static\\images', upload_to=''),
        ),
    ]
