# Generated by Django 4.2.7 on 2023-12-09 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0005_alter_book_book_url_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='books_id',
            new_name='books',
        ),
        migrations.AlterField(
            model_name='cart',
            name='time_order',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 5, 58, 51, 189883)),
        ),
    ]
