# Generated by Django 4.2.7 on 2023-12-09 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0006_rename_books_id_cart_books_alter_cart_time_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='time_order',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 6, 4, 13, 337819)),
        ),
    ]
