# Generated by Django 4.2.7 on 2023-12-09 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0007_alter_cart_time_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='books',
            field=models.ManyToManyField(to='BookAPI.book'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='time_order',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 6, 34, 59, 314947)),
        ),
    ]
