# Generated by Django 4.2.7 on 2023-12-11 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0008_alter_book_author_name_alter_book_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='time_order',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 20, 51, 10, 550237)),
        ),
    ]
